# Generated by Django 3.1b1 on 2020-11-24 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archivewebsite', '0002_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
