# Generated by Django 3.1b1 on 2020-11-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20201124_0523'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
