# Generated by Django 3.1.4 on 2021-01-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='First_advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Second_advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
